name: Continuous Scraping

on:
  workflow_dispatch:
  schedule:
    # every 13 hours
    - cron:  '*/15 * * * *'

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Checkout"
  Fetch:
    needs: Checkout
    runs-on: ubuntu-latest
    steps:
    - run: echo "Fetch"
  Filter and Transform:
    needs: Fetch
    runs-on: ubuntu-latest
    steps:
    - run: echo "Filter & Transform"
  Check and Update:
    needs: Filter and Transform
    runs-on: ubuntu-latest
    steps:
    - run: echo "Check & Update"
  Collect:
    needs: Check and Update
    runs-on: ubuntu-latest
    steps:
    - run: echo "Collect"
