name: Continuous Scraping

on:
  workflow_dispatch:
  schedule:
    # every 13 hours
    - cron:  '*/15 * * * *'

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Checkout"
  Fetch:
    needs: Checkout
    runs-on: ubuntu-latest
    steps:
    - run: echo "Fetch"
  FilterAndTransform:
    needs: Fetch
    runs-on: ubuntu-latest
    steps:
    - run: echo "Filter & Transform"
  CheckAndUpdate:
    needs: FilterAndTransform
    runs-on: ubuntu-latest
    steps:
    - run: echo "Check & Update"
  Collect:
    needs: CheckAndUpdate
    runs-on: ubuntu-latest
    steps:
    - run: echo "Collect"
